sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: *************
    access-key-secret: ************
    bucket-name: sky-itcast-sumuzi
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 10
  wechat:
    appid: wxe03d3bb8fe06c436
    secret: d9de4ff9629bfc111543fd2afe82ea62